---
name: deploy
runner_type: action-chain
description: Deploy pack to StackStorm host
enabled: true
entry_point: 'workflows/pack_deploy.yaml'
parameters:
  pack:
    type: string
    description: Name of the pack to be deployed
    required: true
  branch:
    type: string
    description: git branch to deploy
    default: 'master'
  repo:
    type: string
    description: Location where to retrieve remote pack from
    default: 'StackStorm/st2contrib'
  subtree:
    type: boolean
    description: Flag to determine whether pack is nested within a repository, or is stand-alone
    default: true
  force:
    type: boolean
    description: Force a destructive action
    default: false
  sudo:
    default: true
