---
  chain:
    -
      name: "lookup_hosts"
      ref: "st2.kv.get"
      params:
        key: "st2.servers"
      publish:
        st2_servers: "{{lookup_hosts.result}}"
      on-success: "get_information"
    -
      name: "get_information"
      ref: "deploy.command"
      params:
        pack: "{{pack}}"
        info: true
        hosts: "{{st2_servers}}"
