# notify_hubot.yaml
---
name: "chatops.notify_hubot"
enabled: true
description: "Notification rule to send messages to Hubot"
trigger:
  pack: "chatops"
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.channel:
    pattern: "hubot"
    type: "equals"
action:
  ref: hubot.post_message
  parameters:
    channel: "#chatops"
    message: "{{trigger.data.result}}"
